server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: con.yukicris.springcloud.pojo
  config-locations: classpath:mybatis/mabatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://yukicris1.com:7001/eureka/,http://yukicris2.com:7002/eureka/,http://yukicris3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8001  #修改Erueka的默认描述信息

#info配置 (配合actuator包,添加一些服务信息)
info:
  app.name: yukicris-springcloud
  company.name: blog.yukicris.com