server:
  port: 7003


#Eureka配置
eureka:
  instance:
    hostname: yukicris3.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false  # 表示是否向eureka注册中心注册自己,现在当前应用就是Eureka Server服务器,不需要注册自己
    fetch-registry: false  #如果为false,表示自己为注册中心
    service-url:   # 监控页面
      defaultZone: http://yukicris1.com:7001/eureka/,http://yukicris2.com:7002/eureka/