server:
  port: 9527

spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9527.com  #信息名称
    prefer-ip-address: true  #是否隐藏ip

info:
  app.name: yukicris-springcloud
  company.name: blog.yukicris.com


zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**     #这个配置是为了隐藏原来的服务路径
  ignored-services: springcloud-provider-dept #不能再使用这个路径访问
  prefix: /yukicris  # 前缀,可以不要 加了的话就必须访问http://www.yukicris.com:9527/yukicris/mydept/dept/get/1